### ISSUE TITLE
OT: what supersedes createShadowRoot?

### ISSUE THREAD

**Issue by dandv** [jpmedley/chrome.docs#2]
Hi @jpmedley,

Sorry for polluting this repo - haven't found a way [at MDN](https://developer.mozilla.org/en-US/profiles/jpmedley) to contact you.

My question regards your edit of [createShadowRoot() at MDN](https://developer.mozilla.org/en-US/docs/Web/API/Element/createShadowRoot). You've marked it as deprecated and I'm curious if there's a recommended alternative. https://hacks.mozilla.org/2015/06/the-state-of-web-components/ doesn't mention one.

**Comment by jpmedley** [comment]
I apologize for the error. It's using multiple shadow roots that's
deprecated. I'll fix it.

Joe Medley | Technical Writer, DevPlat | jmedley@google.com | 816-678-7195
